name = "H3"
uuid = "f62fece2-b996-571a-b4c9-e662aba1c617"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.3.3-DEV"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
H3_jll = "60c8821e-da38-5dbd-93c7-983f1e6d69be"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CEnum = "0.5"
H3_jll = "4.2"
Jive = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]
